INSERT INTO products (name, description, price, category_id, image_url, stock, fabricante, descrip_fabricante)
VALUES
    ('Nave espacial', '¡Despega hacia aventuras intergalácticas!', 20.00, 1, 'assets/images/prod-1.jpg', 50, 'Voyagers Inc', 'Voyagers Inc. especializa en juguetes espaciales que inspiran a jóvenes astronautas. Nuestra nave espacial promueve la imaginación y la exploración intergaláctica en los niños.'),
    ('Bloques Lego', '¡Desata un mundo de creatividad!', 15.00, 1, 'assets/images/prod-2.jpg', 40, 'Blocks Co','Creative Blocks Co. ofrece bloques de construcción que fomentan la creatividad y el desarrollo cognitivo. Nuestros juguetes son perfectos para construir mundos infinitos.'),
    ('Muñeca de peluche', 'Encuentra una amiga tierna y cariñosa.', 25.00, 1, 'assets/images/prod-3.jpg', 35, 'Tender Hugs Toys','Tender Hugs Toys crea muñecas de peluche diseñadas para ser amigas tiernas y duraderas. Nuestros peluches son suaves, seguros y perfectos para abrazar.'),
    ('Puzzle de animales', '¡Embárcate en una aventura de descubrimiento!', 10.00, 1, 'assets/images/prod-4.jpg', 30, 'Wild Discoveries Puzzles','Wild Discoveries Puzzles ofrece rompecabezas educativos para explorar el reino animal. Nuestros puzzles son una aventura de aprendizaje y diversión.'),
    ('Tren de juguete', '¡Todos a bordo del Tren Express!', 30.00, 1, 'assets/images/prod-5.jpg', 20, 'Express Trains Ltd','Express Trains Ltd. se dedica a crear trenes de juguete realistas y emocionantes. Nuestros trenes promueven el juego interactivo y la imaginación.'),
    ('Coche radiocontrol', '¡Prepárate para la acción a toda velocidad!', 45.00, 1, 'assets/images/prod-6.jpg', 25, 'Speedster Remote Cars','Speedster Remote Cars produce coches a control remoto para una acción emocionante y rápida. Nuestros modelos son duraderos y diseñados para aventuras.'),
    ('Set de dinosaurios', '¡Retrocede en el tiempo a una era prehistórica!', 28.00, 1, 'assets/images/prod-7.jpg', 15, 'Prehistoric Playsets','Prehistoric Playsets revive la era de los dinosaurios con sets detallados y educativos. Nuestros juguetes incentivan el interés en la historia natural.'),
    ('Juego de mesa', '¡Sumérgete en un mundo de tácticas!', 18.00, 1, 'assets/images/prod-8.jpg', 22, 'Strategy Games Guild','Strategy Games Guild crea juegos de mesa desafiantes que fomentan la táctica y el pensamiento crítico. Nuestros juegos son perfectos para noches familiares.'),
    ('Robot interactivo', '¡Conoce a tu nuevo compañero futurista!', 50.00, 1, 'assets/images/prod-9.jpg', 18, 'Future Friends Robotics','Future Friends Robotics se especializa en robots interactivos que enseñan programación y amistad. Nuestros robots son compañeros futuristas y educativos.'),
    ('Kit de ciencia', '¡Embárcate en una emocionante travesía científica!', 20.00, 1, 'assets/images/prod-10.jpg', 28, 'Young Explorers Lab','Young Explorers Lab ofrece kits de ciencia para jóvenes científicos curiosos. Nuestros kits son seguros, divertidos y promueven el descubrimiento científico.'),
    ('Osito de peluche', '¡Este adorable osito de peluche es el compañero perfecto!', 27.00, 1, 'assets/images/prod-11.jpg', 68, 'Cuddle Bear Creations','Cuddle Bear Creations produce ositos de peluche adorables y suaves. Son el compañero perfecto para abrazar y compartir aventuras.'),
    ('Piano de juguete', '¡Descubre la alegría de la música con nuestro piano de juguete!', 31.00, 1, 'assets/images/prod-12.jpg', 17, 'Melody Makers Toys','Melody Makers Toys inspira a los jóvenes músicos con pianos de juguete. Nuestros instrumentos son ideales para introducir a los niños en la música.');